import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import TestComponent from "../components/TestComponent";
import Calendar from "react-calendar";
import "react-calendar/dist/Calendar.css";
import React, { useEffect } from "react";
import { useState } from "react";
import { languages } from "../../data/expConst";
import Select from "react-select";
const Home: NextPage = () => {
  const [value, onChange] = useState(new Date());
  const [language, onChangeLang] = useState();
  const defaultOption = languages[0];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className={styles.titleClass}>Middlebury Language Tables</div>
        <div className={styles.selectLangClass}>
          <span>Language:</span>{" "}
          <span>
            {" "}
            <Select options={languages} onChange={onChangeLang} />{" "}
          </span>
        </div>
        <div className={styles.calenderClass}>
          {" "}
          <Calendar onChange={onChange} value={value} />
        </div>
        <div className={styles.titleClass}>
          {" "}
          {value.toString().slice(0, 10)} for{" "}
          {language ? language.label : "NONE"}
        </div>
      </div>
    </div>
  );
};

export default Home;
