import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Calendar from "react-calendar";
import "react-calendar/dist/Calendar.css";
import React, { useEffect } from "react";
import { useState } from "react";
import { languages, courses } from "./../../data/expConst";
import Select from "react-select";
import styles from "./../styles/Home.module.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import Swal from "sweetalert2";
import MakeReservation from "./components/MakeReservation";
import CancelReservation from "./components/CancelReservation";

import "react";

function Home() {
  //define our states so we can access the data the user types
  const [dateValue, onDateChange] = useState(new Date());
  const [option, setOption] = useState("make");

  return (
    <div className={styles.container}>
      <Head>
        <title>LT Reservation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
          crossOrigin="anonymous"
        />
      </Head>
      <Container>
        <div className={styles.headerClass}>
          <div className={styles.titleClass}>Middlebury Language Tables</div>
        </div>
        <Row className="row item" style={{ paddingTop: "150px" }}>
          <Col md={1}></Col>
          {/* calender selection column */}
          <Col md={4}>
            <div className={styles.calenderClass}>
              {" "}
              <Calendar onChange={onDateChange} value={dateValue} />
            </div>
          </Col>

          <Col md={1}></Col>

          {/* selection boxes */}
          <Col md={6}>
            <Container>
              <div>
                {/* buttons to select which one */}
                <div
                  style={{ display: "flex", padding: "10px", width: "100%" }}
                >
                  {option == "make" ? (
                    <div style={{ width: "100%" }}>
                      <button
                        style={{
                          width: "50%",
                          backgroundColor: "red",
                          textAlign: "center",
                          padding: "5px",
                        }}
                        onClick={(e) => setOption("make")}
                      >
                        Make
                      </button>
                      <button
                        style={{
                          width: "50%",
                          backgroundColor: "white",
                          textAlign: "center",
                          padding: "5px",
                        }}
                        onClick={(e) => setOption("cancel")}
                      >
                        Cancel
                      </button>
                    </div>
                  ) : (
                    <div style={{ width: "100%" }}>
                      <button
                        style={{
                          width: "50%",
                          backgroundColor: "white",
                          textAlign: "center",
                          padding: "5px",
                        }}
                        onClick={(e) => setOption("make")}
                      >
                        Make
                      </button>
                      <button
                        style={{
                          width: "50%",
                          backgroundColor: "red",
                          textAlign: "center",
                          padding: "5px",
                        }}
                        onClick={(e) => setOption("cancel")}
                      >
                        Cancel
                      </button>
                    </div>
                  )}
                </div>
              </div>
              {option == "make" ? (
                <MakeReservation date={dateValue} />
              ) : (
                <CancelReservation date={dateValue} />
              )}
            </Container>
          </Col>
        </Row>
      </Container>
    </div>
  );
}

export default Home;
